name: Build CycloneDDS

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  cyclonedds:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64]

    runs-on: ubuntu-latest

    steps:
    - name: Clone
      run: |
        git clone --depth 1 https://github.com/eclipse-cyclonedds/cyclonedds.git
        cd cyclonedds

    - name: Set up dependancies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake

    - name: Build
      run: |
        cd cyclonedds
        mkdir build
        cd build
        cmake -DCPACK_PACKAGING_INSTALL_PREFIX=/opt/inclination ..
        cmake --build .
        cpack -G DEB
        find . -name '*.deb' -exec dpkg -c {} \;

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: eclipse-cyclone-dds-${{ matrix.arch }}
        path: cyclonedds/build/*.deb

  cyclonedds-python:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64]
    runs-on: ubuntu-latest
    needs: cyclonedds
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: eclipse-cyclone-dds-${{ matrix.arch }}
        path: artifacts
    - name: Clone
      run: |
        git clone --depth 1 https://github.com/eclipse-cyclonedds/cyclonedds-python.git
        cd cyclonedds-python
    - name: Set up dependencies
      run: |
        sudo apt update
        #find artifacts
        #dpkg -c artifacts/eclipse-cyclone-dds_0.11.0_amd64.deb
        sudo apt install -y ./artifacts/*.deb
        #find /opt/inclination
    - name: Build
      run: |
        CYCLONEDDS_HOME=/opt/inclination python3 -m build --sdist --wheel

